#
# /tp @s -532 91 189
#

on load:
    set {_id} to "secret_cave"
    if {AREA::%{_id}%} is not set:
        set {AREA::%{_id}%} to {_id}

        set {AREA::%{_id}%::TITLE} to "秘密の洞窟"
        set {AREA::%{_id}%::SUBTITLE} to "隠しエリア"

        add "え？ここ見つけられたの？やるじゃん (蟹。)" to {AREA::%{_id}%::DESCRIPTION::*}

        add location(x: -532, y: 91, z: 189) and location(x: -530, y: 96, z: 196) to {AREA::%{_id}%::RANGE::1::*}
