#
# 参加時に
#

on join:
    # タイトル
    reset title of player
    send title "§c§o= §r蟹鯖へようこそ！§c§o =" to player for 2 seconds with fade in 1 second and fade out 1 second

    # 音
    play sound "entity.firework_rocket.launch" with volume 0.25 with pitch 2.00 to player
    play sound "entity.firework_rocket.launch" with volume 1.00 with pitch 1.00 to player
    play sound "entity.firework_rocket.launch" with volume 0.25 with pitch 0.00 to player

    # エリア情報を消す
    initArea("%uuid of player%")
